[features]
seeds = false
[programs.localnet]
anchor_helloworld = "D1oA4g1uwn6QE24GxpsLixa5UaMn3oRNqUa4d91Qu7ru"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/he.qiming/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
